variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t2.medium"
}

variable "allowed_ssh_cidr" {
  description = "CIDR block allowed to SSH into the instance"
  type        = string
  default     = "0.0.0.0/0"
}

variable "domain_name" {
  description = "Domain name for the application"
  type        = string
}

variable "github_repo_url" {
  description = "GitHub repository URL to clone"
  type        = string
}

variable "ssh_private_key_path" {
  description = "Path to SSH private key for Ansible (used in inventory template)"
  type        = string
  default     = "~/.ssh/deploy_key"
}

variable "key_name" {
  description = "Name of AWS key pair (deprecated - now generated by Terraform)"
  type        = string
  default     = "todo-app-deploy-key"
}

variable "email_for_alerts" {
  description = "Email address for drift detection alerts"
  type        = string
  default     = ""
}
